apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: x57f9qzro-nodejs
  janus-idp.io/tekton: x57f9qzro-nodejs
  backstage.io/kubernetes-id: x57f9qzro-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: x57f9qzro-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
