apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: x57f9qzro-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: x57f9qzro-nodejs 
  name: x57f9qzro-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: x57f9qzro-nodejs 
